name: Test
on:
  push:
    branches:
      - '**'
  pull_request: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22]
    uses: ./.github/workflows/base.yaml
    with:
      node-version: ${{ matrix.node-version }}
      go-version: 1.22
      upload: false
